[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo_mysql",
    "php82Extensions.mbstring",
    "php82Extensions.fileinfo",
    "php82Extensions.tokenizer",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "php82Extensions.zip",
    "php82Extensions.bcmath",
    "nginx"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "sh start.sh"